version: "2.4"
services:
  web:
    image: nginx
    container_name: web
    restart: unless-stopped
    volumes:
      - ./volumes/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../web:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      
  php:    
    image: php:7.0-fpm  
    container_name: php
    restart: unless-stopped
    volumes:
      - ./volumes/nginx.conf:/etc/nginx/nginx.conf:ro
