version: "2.4"
services:
  web:
    image: nginx
    container_name: web
    volumes:
      - ./volumes/nginx.conf:/usr/share/nginx/html:ro
      - ../web:/usr/share/nginx/html:ro
    ports:
      - "80:80"

